### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by rogerlee0518**

### CODE REVIEW

**Comment by jpkli** [comment]
Please do not upload the .DS_Store files to the repository.

**Comment by jpkli** [comment]
Please remove the .DS_Store files by undoing the commit. After removing the files, please commit again.

**Comment by rogerlee0518** [comment]
Hi Kelvin,

Sorry for the inconvenience. I just committed it again. Do I need to do
another pull request or resubmit the homework on Canvas? Thank you!

Sincerely,

Roger Lee

Kelvin Li <notifications@github.com> 於 2020年1月8日 週三 上午12:27寫道：

**Comment by jpkli** [comment]
You don't need to create another pull request, just modify your repository will send updates to this pull request. For the name of your HTML file, you should not name it "index.html", please follow the submission instruction provided in the assignment.

**Comment by rogerlee0518** [comment]
Okay just updated. Thank you so much for your help!

Roger Lee

Kelvin Li <notifications@github.com> 於 2020年1月8日 週三 上午11:42寫道：

**Pull request merged**
